theme: jekyll-theme-minimal
title: Mainsail Themes homepage
description: Bookmark this to keep an eye on my project updates!

layout: page
title: "Startseite"
permalink: https://github.com/bumbeng/mainsail-themes.github.io/blob/main/Startseite.html

layout: page
title: "Mainsail"
permalink: https://github.com/bumbeng/mainsail-themes.github.io/blob/main/Mainsail.html

